<?php
/**
 * Plugin Name: Smart Product Approval Manager
 * Description: React-style product approval dashboard (demo). Provides REST APIs and a simple admin UI.
 * Version: 1.0
 * Author: Generated by ChatGPT
 */

if (!defined('ABSPATH')) exit;

define('SPAM_PATH', plugin_dir_path(__FILE__));
define('SPAM_URL', plugin_dir_url(__FILE__));

require_once SPAM_PATH . 'includes/installer.php';
require_once SPAM_PATH . 'includes/class-rest-controller.php';
require_once SPAM_PATH . 'includes/class-approval-service.php';
require_once SPAM_PATH . 'includes/class-product-logger.php';

register_activation_hook(__FILE__, ['SPAM_Installer', 'install']);

add_action('admin_menu', function () {
    add_menu_page(
        'Product Approvals',
        'Approvals',
        'manage_options',
        'spam-approvals',
        function () {
            echo '<div class="wrap"><h1>Smart Product Approval Manager</h1><div id="spam-root"></div></div>';
        }
    );
});

add_action('admin_enqueue_scripts', function () {
    wp_enqueue_script('spam-app', SPAM_URL . 'build/bundle.js', [], null, true);
    wp_localize_script('spam-app', 'spamApi', [
        'root' => esc_url_raw(rest_url('spam/v1/')),
        'nonce' => wp_create_nonce('wp_rest')
    ]);
    wp_enqueue_style('spam-style', SPAM_URL . 'build/style.css');
});

add_action('rest_api_init', ['SPAM_Rest_Controller', 'init']);
